// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MonitoringService;
using System;

namespace MonitoringService.Migrations
{
    [DbContext(typeof(MonitoringContext))]
    [Migration("20180513030408_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonitoringService.Models.Entities.AgentState", b =>
                {
                    b.Property<int>("AgentStateId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgentId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("ReportDate");

                    b.HasKey("AgentStateId");

                    b.ToTable("AgentStates");
                });

            modelBuilder.Entity("MonitoringService.Models.Entities.Error", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgentStateId");

                    b.Property<string>("Message");

                    b.HasKey("ErrorId");

                    b.HasIndex("AgentStateId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("MonitoringService.Models.Entities.Error", b =>
                {
                    b.HasOne("MonitoringService.Models.Entities.AgentState", "AgentState")
                        .WithMany("Errors")
                        .HasForeignKey("AgentStateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
