// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MonitoringService;
using System;

namespace MonitoringService.Migrations
{
    [DbContext(typeof(MonitoringContext))]
    partial class MonitoringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("MonitoringService.Models.AgentInfo", b =>
                {
                    b.Property<int>("AgentInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgentId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<int?>("ReportId");

                    b.HasKey("AgentInfoId");

                    b.HasIndex("ReportId");

                    b.ToTable("AgentInfos");
                });

            modelBuilder.Entity("MonitoringService.Models.Error", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgentInfoId");

                    b.Property<string>("Message");

                    b.HasKey("ErrorId");

                    b.HasIndex("AgentInfoId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("MonitoringService.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MonitoringService.Models.AgentInfo", b =>
                {
                    b.HasOne("MonitoringService.Models.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId");
                });

            modelBuilder.Entity("MonitoringService.Models.Error", b =>
                {
                    b.HasOne("MonitoringService.Models.AgentInfo", "AgentInfo")
                        .WithMany("Errors")
                        .HasForeignKey("AgentInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
